apiVersion: v1
kind: Secret
metadata:
  name: additional-ca
  namespace: hive
stringData:
{% if mce_hive_additional_ca | length > 0 %}
  ca.crt: |
    {{ mce_hive_additional_ca | indent(4) }}
{% else %}
  ca.crt: ''
{% endif %}
