apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  additionalOptions:
  # The proxy and proxy-headers settings are required for edge-terminated ingress
  # See also: https://github.com/keycloak/keycloak/issues/15107
  - name: proxy
    value: edge
  # Suppress warning: A ServiceMonitor will not be created because `metrics-enabled` is not true.
  - name: metrics-enabled
    value: 'true'
  instances: 1
  db:
    vendor: postgres
    host: keycloak-postgresql
    usernameSecret:
      name: keycloak-postgresql-creds
      key: username
    passwordSecret:
      name: keycloak-postgresql-creds
      key: password
  hostname:
    # Hostname must be set or the Ingress object won't create the respective Route
    hostname: {{ rhbk_instance_hostname }}
  ingress:
    enabled: true
    className: openshift-default
  http:
    # This will create an edge-terminated Route
    httpEnabled: true
  proxy:
    # The proxy headers that should be accepted by the server.
    headers: forwarded
{% if rhbk_trusted_ca_cert | length > 0 %}
  truststores:
    trusted-ca-bundle:
      secret:
        name: trusted-ca
{% endif %}
