apiVersion: forklift.konveyor.io/v1beta1
kind: NetworkMap
metadata:
  name: migration1
  namespace: openshift-mtv
spec:
  map:
  - destination:
      type: pod
    source:
      type: pod
  provider:
    destination:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: mycluster5
      namespace: openshift-mtv
    source:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: host
      namespace: openshift-mtv
