apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    alerts.k8s.io/KubePersistentVolumeFillingUp: disabled
  name: m1mycluster4-rootdisk
  namespace: mycluster4-infraenv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
  volumeMode: Filesystem
