apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
  namespace: trusted-profile-analyzer
spec:
  secretStoreRef:
    name: autogitops
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      nullBytePolicy: Ignore
      key: '{{ oscommon_cluster_domain }}/trusted-profile-analyzer/instance/keycloak-credentials'
