###################
# Common settings #
###################

interface=eth0
except-interface=lo

# Do not go into the background at startup but otherwise run as normal
keep-in-foreground

# If the log facility is '-' then dnsmasq logs to stderr
log-facility=-

{% if osinfralibvirt_dhcp_enabled %}
#################
# DHCP settings #
#################

dhcp-range=192.168.{{ osinfralibvirt_lab_number }}0.20,192.168.{{ osinfralibvirt_lab_number }}0.254,255.255.255.0
dhcp-no-override
dhcp-authoritative

# Set the "domain" DHCP option
domain={{ osinfralibvirt_cluster_name }}.example.com

# Set further DHCP options
dhcp-option=option:router,192.168.{{ osinfralibvirt_lab_number }}0.1
dhcp-option=option:netmask,255.255.255.0
dhcp-option=option:dns-server,192.168.{{ osinfralibvirt_lab_number }}0.2

# Log DHCP requests and responses
log-dhcp

# Reserved (fixed) host IP addresses
{% for i in range(1, osinfralibvirt_cluster_bootstrap_count + 1) %}
dhcp-host=52:54:00:0{{ osinfralibvirt_lab_number }}:{{ 19 + i }}:00,b{{ i }}{{ osinfralibvirt_cluster_name }},192.168.{{ osinfralibvirt_lab_number }}0.{{ 19 + i }}
{% endfor %}
{% for i in range(1, osinfralibvirt_cluster_master_count + 1) %}
dhcp-host=52:54:00:0{{ osinfralibvirt_lab_number }}:{{ 20 + i }}:00,m{{ i }}{{ osinfralibvirt_cluster_name }},192.168.{{ osinfralibvirt_lab_number }}0.{{ 20 + i }}
{% endfor %}
{% for i in range(1, osinfralibvirt_cluster_worker_count + 1) %}
dhcp-host=52:54:00:0{{ osinfralibvirt_lab_number }}:{{ 30 + i }}:00,w{{ i }}{{ osinfralibvirt_cluster_name }},192.168.{{ osinfralibvirt_lab_number }}0.{{ 30 + i }}
{% endfor %}

{% endif %}
################
# DNS settings #
################

# Don't forward queries for names in these domains
local=/{{ osinfralibvirt_cluster_name }}.example.com/
local=/apps.{{ osinfralibvirt_cluster_name }}.example.com/
local=/{{ osinfralibvirt_lab_number }}0.168.192.in-addr.arpa/

# Ignore names in /etc/hosts
no-hosts

# Prevent maximum number of concurrent DNS queries reached (default is 150)
dns-forward-max=4096

# Log DNS queries
#log-queries

# Log DNS extra information
#log-queries=extra

# Kubernetes API records
{% if osinfralibvirt_external_loadbalancer %}
host-record=api.{{ osinfralibvirt_cluster_name }}.example.com,192.168.{{ osinfralibvirt_lab_number }}0.2
host-record=api-int.{{ osinfralibvirt_cluster_name }}.example.com,192.168.{{ osinfralibvirt_lab_number }}0.2
{% else %}
host-record=api.{{ osinfralibvirt_cluster_name }}.example.com,192.168.{{ osinfralibvirt_lab_number }}0.10
host-record=api-int.{{ osinfralibvirt_cluster_name }}.example.com,192.168.{{ osinfralibvirt_lab_number }}0.10
{% endif %}

# Wildcard DNS record
{% if osinfralibvirt_external_loadbalancer %}
address=/apps.{{ osinfralibvirt_cluster_name }}.example.com/192.168.{{ osinfralibvirt_lab_number }}0.2
{% else %}
address=/apps.{{ osinfralibvirt_cluster_name }}.example.com/192.168.{{ osinfralibvirt_lab_number }}0.11
{% endif %}

# Node DNS records
{% for i in range(1, osinfralibvirt_cluster_bootstrap_count + 1) %}
host-record=b{{ i }}{{ osinfralibvirt_cluster_name }}.{{ osinfralibvirt_cluster_name }}.example.com,192.168.{{ osinfralibvirt_lab_number }}0.{{ 19 + i }}
{% endfor %}
{% for i in range(1, osinfralibvirt_cluster_master_count + 1) %}
host-record=m{{ i }}{{ osinfralibvirt_cluster_name }}.{{ osinfralibvirt_cluster_name }}.example.com,192.168.{{ osinfralibvirt_lab_number }}0.{{ 20 + i }}
{% endfor %}
{% for i in range(1, osinfralibvirt_cluster_worker_count + 1) %}
host-record=w{{ i }}{{ osinfralibvirt_cluster_name }}.{{ osinfralibvirt_cluster_name }}.example.com,192.168.{{ osinfralibvirt_lab_number }}0.{{ 30 + i }}
{% endfor %}
