- ansible.builtin.import_role:
    name: openshift_webhook_receiver
    tasks_from: delete.yml
  vars:
    webhookreceiver_namespace: stackrox
    webhookreceiver_manage_namespace: false
    webhookreceiver_app_prefix: rhacs-
