apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ oauthproxy_name }}
spec:
  port:
    targetPort: oauth-proxy
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: {{ oauthproxy_name }}-oauth-proxy
