apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ oauthproxy_name }}-oauth-proxy-k8s-tls
  name: {{ oauthproxy_name }}-oauth-proxy
spec:
  selector:
    app: {{ oauthproxy_name }}-oauth-proxy
  ports:
  - name: oauth-proxy
    port: 9091
