apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/name: kubevirt-redfish
    app.kubernetes.io/component: config
  name: kubevirt-redfish
  namespace: kubevirt-redfish
spec:
  secretStoreRef:
    name: autogitops
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      nullBytePolicy: Ignore
      key: '{{ oscommon_cluster_domain }}/kubevirt-redfish/instance/config'
