- name: Set hostname if it was not set properly
  ansible.builtin.hostname:
    name: '{{ inventory_hostname_short }}'
  register: machinebase_hostname_result
  become: true

- name: Run setup after the hostname changed
  ansible.builtin.setup:
  when: machinebase_hostname_result is changed
