- name: Get list of VMs
  community.libvirt.virt:
    command: list_vms
  register: osinfralibvirt_list_vms_result

- name: VM {{ lab_command }}
  community.libvirt.virt:
    name: '{{ item.hostname }}'
    command: '{{ lab_command }}'
  when: item.hostname in osinfralibvirt_list_vms_result.list_vms
  loop: '{{ osinfralibvirt_nodes }}'
