- name: Delete domain XML definition
  ansible.builtin.file:
    path: '{{ osinfralibvirt_dir }}/domains/{{ item.hostname }}.xml'
    state: absent
  loop: '{{ osinfralibvirt_nodes }}'
  loop_control:
    label: '{{ item.hostname }}'
