- name: Add bootstrap node
  ansible.builtin.set_fact:
    osinfralibvirt_nodes: >-
      {{ osinfralibvirt_nodes | default([]) + [
        { "hostname": "b1" ~ osinfralibvirt_cluster_name,
          "number": 20
        }]
      }}
  loop: '{{ range(1, osinfralibvirt_cluster_bootstrap_count + 1) | list }}'

- name: Add master nodes
  ansible.builtin.set_fact:
    osinfralibvirt_nodes: >-
      {{ osinfralibvirt_nodes | default([]) + [
        { "hostname": "m" ~ item ~ osinfralibvirt_cluster_name,
          "number": 20 + item
        }]
      }}
  loop: '{{ range(1, osinfralibvirt_cluster_master_count + 1) | list }}'

- name: Add worker nodes
  ansible.builtin.set_fact:
    osinfralibvirt_nodes: >-
      {{ osinfralibvirt_nodes | default([]) + [
        { "hostname": "w" ~ item ~ osinfralibvirt_cluster_name,
          "number": 30 + item
        }]
      }}
  loop: '{{ range(1, osinfralibvirt_cluster_worker_count + 1) | list }}'
